[package]
name = "katla"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2021"

[dependencies]
katla_math = { path = "../katla_math" }
katla_vulkan = { path = "../katla_vulkan" }
katla_ecs = { path = "../katla_ecs" }
byteorder = "1.3"
winit = "^0.30"
image = "0.23.11"
env_logger = "0.9.0"
gltf = { version = "^1.3", features = ["KHR_materials_pbrSpecularGlossiness"] }
itertools = "0.14.0"
