[package]
name = "katla_ecs"
version = "0.1.0"
authors = ["Mik-pe <mikael.pettersson201@gmail.com>"]
edition = "2021"

[dependencies]
katla_derive = { path = "../katla_derive" }
katla_math = { path = "../katla_math" }
